version: '3.5'

volumes:
    postgres:
    mysql:

services:
    postgres:
        container_name: docker_ide_postgres
        image: postgres:9
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "justdoit"
            POSTGRES_PASSWORD: "justdoit"
            POSTGRES_DB: "justdoit"

